spring:
  rsocket:
    server:
      port: 7000
      transport: tcp
      mapping-path: /api
  application:
    name: backend
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
    url: r2dbc:h2:file:///./data/scrum-db
    username: su
    password: su
  flyway:
    url: jdbc:h2:file:./data/scrum-db
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
token:
  signing:
    key: C4WYY2KCAGP9STF0YDCGYB71JAJ6QA28T30BWAKVFFJ2IWOC16IK9IYUAMI5E76L